### ISSUE TITLE
Case-insensitive parsing of Org keywords

### ISSUE THREAD

**Issue by kaushalmodi** [hasu/notdeft#2]
Hello,

Can you please enable case-insensitive parsing of Org keywords?

From [my earlier comment][3]:

> >Yes, any #+TITLE keyword is parsed in a case sensitive manner, currently. I'm not sure if lowercase in-buffer setting keywords are exactly documented syntax for Org—haven't seen it stated explicitly in the docs.

> Org actually parses **all** `#+` keywords in case-insensitive fashion. There even was a [commit][2] few months back that showed the preference to use lower-case keywords. (I liked that very much and even have a little [helper function][1] to lower-case all keywords in the current Org document 😄 ).

[1]: https://scripter.co/org-keywords-lower-case/
[2]: https://code.orgmode.org/bzg/org-mode/commit/13424336a6f30c50952d291e7a82906c1210daf0>
[3]: https://github.com/hasu/notdeft/issues/1#issuecomment-386617267

**Comment by hasu** [comment]
I've pushed a commit to make the keyword parsing case insensitive during indexing.

Turns out this was a bug and not a feature request, since the parsing was already case insensitive on the Emacs Lisp side (didn't know it was the default for regexps), meaning that the parsing behavior was inconsistent.

Thank you for the bug report and for pointing out the preference to use lower-case keywords in Org.

**Comment by kaushalmodi** [comment]
Thank you! I confirm the fix!
